#!/usr/bin/env bash

set -e

TARGET=$1

if [ -z "${TARGET}" ]; then
	echo "Target is missing."
	exit 1
fi

if [ ! -f "targets/${TARGET}/config" ]; then
	echo "Target not supported (${TARGET})."
	exit 1
fi

# Packages
sudo apt-get update
sudo apt-get install -y --no-install-recommends \
  automake \
  bison \
  bzip2 \
  ca-certificates \
  cmake \
  curl \
  file \
  flex \
  g++ \
  gawk \
  gdb \
  git \
  gperf \
  help2man \
  libncurses-dev \
  libssl-dev \
  libtool-bin \
  make \
  patch \
  pkg-config \
  python3 \
  rsync \
  texinfo \
  unzip \
  wget \
  xz-utils

# Patch
pushd builder
git reset --hard HEAD
git clean -fdx
for i in ../targets/${TARGET}/*; do
    if [[ $i == *.patch ]]; then
        patch -Np1 -i $i
    fi
done
popd

# crosstool-ng
sudo mkdir -p /opt
sudo rm -rf /opt/ct-ng
pushd builder
./bootstrap
./configure --prefix=/opt/ct-ng
make -j`nproc`
sudo make install
popd

# Build
sudo rm -rf build
mkdir build
pushd build
cp ../targets/${TARGET}/config .config
cat << 'EOF' >> .config
CT_CONFIG_VERSION="4"
CT_EXPERIMENTAL=y
CT_LOCAL_TARBALLS_DIR="../source-tarballs"
CT_PREFIX_DIR="musl-cross"
CT_CONNECT_TIMEOUT=120
CT_DOWNLOAD_WGET_OPTIONS="--tries=20 -nc --progress=dot:binary"
# CT_LOG_PROGRESS_BAR is not set
# CT_SHOW_CT_VERSION is not set
EOF
/opt/ct-ng/bin/ct-ng olddefconfig
echo -e "\n*** CT config ***\n"
cat .config
echo -e "\n******\n"

/opt/ct-ng/bin/ct-ng build

find -maxdepth 2 "musl-cross" -exec chmod +w {} \;
mkdir -p "musl-cross/lib"
rm -f "musl-cross/build.log.bz2"
rm -f "musl-cross/toolchain.cmake"
rm -f "musl-cross/share/${TARGET}-ct-ng.config.bz2"
find -maxdepth 2 "musl-cross" -exec chmod a-w {} \;

# Tarball
sudo rm -rf ${TARGET}
mv musl-cross ${TARGET}
sudo chown -R root:root ${TARGET}
name=$TARGET
sudo tar -cJvf ../${name}.tar.xz ${TARGET}
sudo sha256sum ../${name}.tar.xz | awk '{ print $1 }' > ../${name}.tar.xz.sha256
popd
sudo rm -rf build
