#!/usr/bin/env bash

# This script only runs on Linux.
# It needs a case-sensitive file system (prerequisite for crosstool-ng).

set -e -o pipefail


function get_build_machine_type()
{
	local system="linux"
	case $(uname -s) in
		Linux) ;;
		*) echo "uname -s: \"$(uname -s)\"" >&2 ;;
	esac
	local arch=""
	case $(uname -m) in
		i?86) arch="x86" ;;
		x86_64|amd64) arch="x64" ;;
		aarch64*|arm64|armv8*) arch="arm64" ;;
		*) echo "uname -m: \"$(uname -m)\"" >&2 ;;
	esac
	if [ -n "$arch" ]; then printf '%s\n' "${system}-${arch}"
	else printf '%s\n' "$system"
	fi
}


function install_packages()
{
	local packages="\
		autoconf \
		automake \
		bison \
		bzip2 \
		flex \
		g++ \
		gawk \
		gcc \
		git \
		gperf \
		help2man \
		libncurses-dev \
		libtool-bin \
		make \
		patch \
		python3 \
		rsync \
		texinfo \
		unzip \
		wget \
		xz-utils \
	"
	sudo apt-get update
	sudo apt-get install -y --no-install-recommends $packages
}


function build_crosstool_ng()
{
	sudo rm -rf crosstool-ng
	mkdir crosstool-ng
	local install_dir="$(pwd)/crosstool-ng"

	pushd builder

	# Patch
	git clean -fdx
	git reset --hard HEAD
	if [ -d "../patches" ]; then
		find "../patches" -type f -name "*.patch" -print0 | sort -z | \
			while IFS= read -r -d '' file; do
				echo "*** ${file#../patches/}"
				patch -Np1 -i "$file"
			done
	fi

	./bootstrap
	./configure --prefix="${install_dir}"
	make -j$(nproc)
	make install
	popd
	sudo chown -R root:0 crosstool-ng

	local name="crosstool-ng.tar.xz"
	echo -e "\nCreating \"${name}\" ...\n"
	tar -cJvf "$name" crosstool-ng
	sudo rm -rf crosstool-ng
}


function build_target()
{
	local TARGET="$1"

	local src_dir="$CTNG_SOURCE_DIR"
	if [ -z "$src_dir" ]; then
		src_dir="source-tarballs"
	fi
	set +e
	local source_dir="$(mkdir -p -- "$src_dir" &>/dev/null && \
		cd -- "$src_dir" &>/dev/null && pwd)"
	set -e
	if [ -z "$source_dir" ]; then
		echo "[ERROR] Source directory invalid (${src_dir})."
		return 1
	fi

	sudo rm -rf crosstool-ng
	tar -xf "crosstool-ng.tar.xz"

	sudo rm -rf build
	mkdir build
	pushd build

	cp "../targets/${TARGET}/config" .config
	cat <<- EOF >> .config
		CT_CONFIG_VERSION="4"
		CT_EXPERIMENTAL=y
		CT_LOCAL_TARBALLS_DIR="${source_dir}"
		CT_PREFIX_DIR="musl-cross"
		CT_CONNECT_TIMEOUT=120
		CT_DOWNLOAD_WGET_OPTIONS="--tries=20 -nc --progress=dot:binary"
		# CT_LOG_PROGRESS_BAR is not set
		# CT_SHOW_CT_VERSION is not set
	EOF
	../crosstool-ng/bin/ct-ng olddefconfig
	echo -e "\n*** CT config ***\n"
	cat .config
	echo -e "\n******\n"

	../crosstool-ng/bin/ct-ng build

	find "musl-cross" -maxdepth 2 -exec chmod +w {} \;
	rm -f "musl-cross/build.log.bz2"
	rm -f "musl-cross/toolchain.cmake"
	rm -f "musl-cross/share/${TARGET}-ct-ng.config.bz2"
	find "musl-cross" -maxdepth 2 -exec chmod a-w {} \;

	# Fix invalid absolute symbolic link
	local linkname="musl-cross/${TARGET}/sysroot/lib/ld-musl-powerpc.so.1"
	if [[ $TARGET == "powerpcle-unknown-linux-musl" && \
		$(readlink "$linkname") == "/usr/lib/libc.so" ]]; then
		pushd "$(dirname "$linkname")"
		echo "Fixing invalid absolute link ${linkname}"
		sudo ln -rsf "../usr/lib/libc.so" "$(basename "$linkname")"
		popd
	fi

	# Tarball
	sudo rm -rf ${TARGET}
	mv musl-cross ${TARGET}
	sudo chown -R root:0 ${TARGET}

	local host_name="$(get_build_machine_type)"

	local name="${host_name}_${TARGET}.tar.xz"
	echo -e "\nCreating \"${name}\" ...\n"
	tar -cJvf "../${name}" "${TARGET}"
	local hash="$(sha256sum "../${name}" | awk '{ print $1 }')"
	printf '%s *%s\n' "$hash" "$name" > "../${name}.sha256"
	popd
	sudo rm -rf build
	sudo rm -rf crosstool-ng

	echo -e "\nThe complete toolchain is in"
	echo -e "${name} .\n"
}


TARGET=$1

if [ -z "$TARGET" ]; then
	echo "[ERROR] Target is missing."
	exit 1
fi

if [[ $TARGET != "crosstool-ng" && ! -f "targets/${TARGET}/config" ]]; then
	echo "[ERROR] Target not supported (${TARGET})."
	exit 1
fi

install_packages

if [ ! -f "crosstool-ng.tar.xz" ]; then
	build_crosstool_ng
fi

if [ "$TARGET" != "crosstool-ng" ]; then
	build_target "$TARGET"
fi

echo -e "\nDone.\n"
