#!/usr/bin/env bash

# This script only runs on Linux.
# It needs a case-sensitive file system (prerequisite for crosstool-ng).

set -e -o pipefail


function get_build_machine_type()
{
	local system="linux"
	case $(uname -s) in
		Linux) ;;
		*) echo "uname -s: \"$(uname -s)\"" >&2 ;;
	esac
	local arch=""
	case $(uname -m) in
		i?86) arch="x86" ;;
		x86_64|amd64) arch="x64" ;;
		aarch64*|arm64|armv8*) arch="arm64" ;;
		*) echo "uname -m: \"$(uname -m)\"" >&2 ;;
	esac
	if [ -n "$arch" ]; then printf '%s\n' "${system}-${arch}"
	else printf '%s\n' "$system"
	fi
}


function install_packages()
{
	local packages="\
		autoconf \
		automake \
		bison \
		bzip2 \
		flex \
		g++ \
		gawk \
		gcc \
		git \
		gperf \
		help2man \
		libncurses-dev \
		libtool-bin \
		make \
		patch \
		python3 \
		rsync \
		texinfo \
		unzip \
		wget \
		xz-utils \
		"
	sudo apt-get update
	sudo apt-get install -y --no-install-recommends $packages
}


function build_target()
{
	local TARGET="$1"

	sudo rm -rf build
	mkdir build
	pushd build
	cp "../targets/${TARGET}/config" .config
	cat <<- EOF >> .config
		CT_CONFIG_VERSION="4"
		CT_EXPERIMENTAL=y
		CT_LOCAL_TARBALLS_DIR="../source-tarballs"
		CT_PREFIX_DIR="musl-cross"
		CT_CONNECT_TIMEOUT=120
		CT_DOWNLOAD_WGET_OPTIONS="--tries=20 -nc --progress=dot:binary"
		# CT_LOG_PROGRESS_BAR is not set
		# CT_SHOW_CT_VERSION is not set
	EOF
	/opt/crosstool-ng/bin/ct-ng olddefconfig
	echo -e "\n*** CT config ***\n"
	cat .config
	echo -e "\n******\n"

	/opt/crosstool-ng/bin/ct-ng build

	find "musl-cross" -maxdepth 2 -exec chmod +w {} \;
	rm -f "musl-cross/build.log.bz2"
	rm -f "musl-cross/toolchain.cmake"
	rm -f "musl-cross/share/${TARGET}-ct-ng.config.bz2"
	find "musl-cross" -maxdepth 2 -exec chmod a-w {} \;

	# Fix invalid absolute symbolic link
	local linkname="musl-cross/${TARGET}/sysroot/lib/ld-musl-powerpc.so.1"
	if [[ $TARGET == "powerpcle-unknown-linux-musl" && \
		$(readlink "$linkname") == "/usr/lib/libc.so" ]]; then
		pushd "$(dirname "$linkname")"
		echo "Fixing invalid absolute link ${linkname}"
		sudo ln -rsf "../usr/lib/libc.so" "$(basename "$linkname")"
		popd
	fi

	# Tarball
	sudo rm -rf ${TARGET}
	mv musl-cross ${TARGET}
	sudo chown -R root:0 ${TARGET}

	local host_name="$(get_build_machine_type)"

	local name="${host_name}_${TARGET}.tar.xz"
	echo -e "\nCreating \"${name}\" ...\n"
	tar -cJvf "../${name}" "${TARGET}"
	local hash="$(sha256sum "../${name}" | awk '{ print $1 }')"
	printf '%s *%s\n' "$hash" "$name" > "../${name}.sha256"
	popd
	sudo rm -rf build
}


TARGET=$1

if [ -z "$TARGET" ]; then
	echo "[ERROR] Target is missing."
	exit 1
fi

if [ ! -f "targets/${TARGET}/config" ]; then
	echo "[ERROR] Target not supported (${TARGET})."
	exit 1
fi

install_packages

# Patch
pushd builder
git reset --hard HEAD
git clean -fdx
for i in ../targets/${TARGET}/*; do
	if [[ $i == *.patch ]]; then
		patch -Np1 -i $i
	fi
done
if [ -d "../patches" ]; then
	cp -rpv "../patches/." "packages/"
fi
popd

# crosstool-NG
sudo mkdir -p /opt
sudo rm -rf /opt/crosstool-ng
pushd builder
./bootstrap
./configure --prefix=/opt/crosstool-ng
make -j`nproc`
sudo make install
popd

build_target "$TARGET"

echo -e "\nDone.\n"
