name: Release

on:
  workflow_dispatch:
  push:
    tags: ['*']

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: true
      matrix:
        target:
          - aarch64-unknown-linux-musl
          - arm-unknown-linux-musleabi
          - arm-unknown-linux-musleabihf
          - armv7-unknown-linux-musleabi
          - armv7-unknown-linux-musleabihf
          - i586-unknown-linux-musl
          - i686-unknown-linux-musl
          - loongarch64-unknown-linux-musl
          - m68k-unknown-linux-musl
          - microblaze-xilinx-linux-musl
          - microblazeel-xilinx-linux-musl
          - mips-unknown-linux-musl
          - mips-unknown-linux-muslsf
          - mipsel-unknown-linux-musl
          - mipsel-unknown-linux-muslsf
          - mips64-unknown-linux-musl
          - mips64el-unknown-linux-musl
          - or1k-unknown-linux-musl
          - powerpc-unknown-linux-musl
          - powerpcle-unknown-linux-musl
          - powerpc64-unknown-linux-musl
          - powerpc64le-unknown-linux-musl
          - riscv32-unknown-linux-musl
          - riscv64-unknown-linux-musl
          - s390x-ibm-linux-musl
          - sh4-multilib-linux-musl
          - x86_64-unknown-linux-musl
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          submodules: true
      - name: Build
        run: |
          sudo rm -rf /opt/*
          ./scripts/make ${{ matrix.target }}
      - name: Upload package
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.target }}.tar.xz
          path: ${{ matrix.target }}.tar.xz
          if-no-files-found: error
          retention-days: 1
      - name: Upload checksum
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.target }}.tar.xz.sha256
          path: ${{ matrix.target }}.tar.xz.sha256
          if-no-files-found: error
          retention-days: 1

  release:
    name: Release
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    needs: [build]
    if: github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          path: release
          pattern: "*.tar.*"
          merge-multiple: true
      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag=${GITHUB_REF#refs/tags/}
          if [ "$(gh release view "$tag" 2>&1)" == "release not found" ]; then
            gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="$tag" \
              --generate-notes --draft
          fi
          for i in release/*.tar.xz; do
            gh release upload "$tag" $i $i.sha256
          done
